import '../styles/globals.css'
import Head from 'next/head'

function MyApp({ Component, pageProps }) {
  return (
    <>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script async src="https://kit.fontawesome.com/236eafeedd.js" crossOrigin="anonymous"></script>
    </Head>
    <Component {...pageProps} />
    </>
  )
}

export default MyApp
